---
title: "Final Report"
subtitle: "due November 16, 2021 by 11:59 PM "
author: "Ashley Bae, Gi Chun, Jay Nolt"
date: "November 2021"
output: pdf_document
---

# Load Packages
```{r load-packages, message = FALSE, warning = FALSE}
library(tidyverse)
library(readxl)
library(dbplyr)
``` 

# Load Data 
```{r load-data, message = FALSE}
load(file = "~/sta198/Jackie-Fan-Club/data/ICPSR_34363/DS0001/34363-0001-Data.rda")
#rename file
data <- da34363.0001
```
Data Citation: Battle, Juan, Pastrana, Antonio Jay, and Daniels, Jessie. Social Justice Sexuality Project: 2010 National Survey, including Puerto Rico. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor], 2013-08-09. https://doi.org/10.3886/ICPSR34363.v1

```{r select-data}
data_filtered <- data %>%
  select(Q15B,
         Q15C,
         Q17A,
         Q17B,
         Q18A1:Q18A5,
         Q18C,
         Q18G,
         Q19A1:Q19A7,
         Q22A,
         Q22B,
         Q25)

# remove descriptions and other attributes
data_filtered2 <- lapply(data, function(x) {attributes(x) <- NULL; x}) %>% 
  as.data.frame() %>%
  select(Q15B,
         Q15C,
         Q17A,
         Q17B,
         Q18A1:Q18A5,
         Q18C,
         Q18G,
         Q19A1:Q19A7,
         Q22A,
         Q22B,
         Q25)
```

```{r renameQuestions}
data <- data_filtered %>%
    select(Q17A,
         Q17B,
         Q18A1:Q18A5,
         Q18C,
         Q18G,
         Q19A1:Q19A7,
         Q22A,
         Q22B,
         Q25) %>%
  rename(healthInsureAcc = Q17A) %>%
  rename(healthProvideAcc = Q17B) %>%
  rename(male = Q18A1) %>%
  rename(female = Q18A2) %>% 
  rename(m2f = Q18A3) %>%
  rename(f2m = Q18A4) %>%
  rename(genderOther = Q18A5) %>%
  rename(sexuality = Q18C) %>%
  mutate(age = 2021 - Q18G) %>%
  rename(black = Q19A1) %>%
  rename(hispanic = Q19A2) %>% 
  rename(asian = Q19A3) %>%
  rename(native = Q19A4) %>%
  rename(white = Q19A5) %>%
  rename(multi = Q19A6) %>%
  rename(raceOther = Q19A7) %>%
  rename(edu = Q22A) %>%
  rename(income = Q22B) %>%
  rename(assessHealth = Q25)
```

```{r creatingGender}
data <- data %>%
  mutate(male = case_when(
  male == "(1) Yes" ~ "male",
  is.na(male) ~ "",
  TRUE ~ ""), 
  female = case_when(
  female == "(1) Yes" ~ "female",
  is.na(female) ~ "",
  TRUE ~ ""), 
  m2f = case_when(
  m2f == "(1) Yes" ~ "m2f",
  is.na(m2f) ~ "",
  TRUE ~ ""), 
  f2m = case_when(
  f2m == "(1) Yes" ~ "f2m",
  is.na(f2m) ~ "",
  TRUE ~ ""), 
  genderOther = case_when(
  genderOther == "(1) Yes" ~ "Other",
  is.na(genderOther) ~ "",
  TRUE ~ ""), 
  gender = ""
) 

data$gender <- paste(data$male, data$female)
data$gender <- paste(data$gender, data$m2f)
data$gender <- paste(data$gender, data$f2m)
data$gender <- paste(data$gender, data$genderOther)

data$gender <- trimws(data$gender)

data <- data %>%
mutate(gender = case_when(
  gender == "male" ~ "Male",
  gender == "female" ~ "Female",
  gender == "m2f" ~ "Transgender: Male to Female",
  gender == "f2m" ~ "Transgender: Female to Male",
  TRUE ~ "Other")
)
```

```{r income-barplot}
ggplot(data, aes(x = income)) +
  geom_bar(fill = "#228b22") +
  labs (x = "Reported Income Level",
        y = "Frequency",
        title = "Distribution of Respondant Income Levels",) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))
```

```{r gender-barplot}
ggplot(data, aes(x = gender)) +
  geom_bar(fill = "light blue") +
  labs (x = "Gender",
        y = "Frequency",
        title = "Distribution of Respondant Gender",) +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))
```
```{r gender-pie-chart}
# Pie Chart with Percentages
gendertable <- table(data$gender)
lbls <- paste(names(gendertable), "\n", gendertable, sep="")
pie(gendertable, labels = lbls,
   main="Pie Chart of Gender Distribution of Respondents") 
```


```{r health-insurance-sexuality}
ggplot(data, aes(x = sexuality,
                         fill = healthInsureAcc)) +
  geom_bar(position = "fill") +
  labs (x = "Sexuality",
        y = "Frequency",
        fill = "Healthcare Insurance Access",
        title = "Distribution of Respondant Sexuality and Healthcare Access") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))
```

```{r health-provider-sexuality}
ggplot(data, aes(x = sexuality,
                         fill = healthProvideAcc)) +
  geom_bar(position = "fill") +
  labs (x = "Sexuality",
        y = "Frequency",
        fill = "Healthcare Provider Access",
        title = "Distribution of Respondant Sexuality and Healthcare Access") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))
```


```{r health-insurance-gender}
ggplot(data, aes(x = gender,
                         fill = healthInsureAcc)) +
  geom_bar(position = "fill") +
  labs (x = "Gender",
        y = "Frequency",
        fill = "Healthcare Insurance Access",
        title = "Distribution of Respondant Gender and Healthcare Access") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))
```

```{r health-provider-gender}
ggplot(data, aes(x = gender,
                         fill = healthProvideAcc)) +
  geom_bar(position = "fill") +
  labs (x = "Gender",
        y = "Frequency",
        fill = "Healthcare Provider Access",
        title = "Distribution of Respondant Gender and Healthcare Access") +
  theme(axis.text.x = element_text(angle = 45,
                                   hjust = 1))
```